---
- name: OS X Global | Trackpad
  osx_defaults:
    key: com.apple.trackpad.scaling
    type: float
    value: 3.0

- name: OS X Global | Do not keep windows
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false

- name: OS X Global | Normal scrolling
  osx_defaults:
    key: com.apple.swipescrolldirection
    type: bool
    value: true

- name: OS X Global | Save panel expanded
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true

- name: OS X Global | Save panel expanded
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true

- name: OS X Global | Use function key to get at special meanings of keys
  osx_defaults:
    key: com.apple.keyboard.fnState
    type: bool
    value: true

- name: OS X Global | Show function keys on the touch bar
  osx_defaults:
    domain: com.apple.touchbar.agent
    key: PresentationModeGlobal
    type: string
    value: functionKeys
  notify: kill touch bar agent

- name: OS X Global | Tab goes through all controls on dialogs
  osx_defaults:
    key: AppleKeyboardUIMode
    type: int
    value: 3

- name: OS X Global | Disable auto correct
  osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Menu bar | Customize menu items
  osx_defaults:
    domain: com.apple.systemuiserver
    key: menuExtras
    type: array
    value:
      - "/System/Library/CoreServices/Menu Extras/Clock.menu"
      - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
      - "/System/Library/CoreServices/Menu Extras/Battery.menu"
      - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"

- name: Menu bar | Show AirPort icon
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible com.apple.menuextra.airport"
    type: bool
    value: true
  notify: kill uiserver

- name: Menu bar | Show battery percentage
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible com.apple.menuextra.battery"
    type: bool
    value: true
  notify: kill uiserver

- name: Menu bar | Show clock
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible com.apple.menuextra.clock"
    type: bool
    value: true
  notify: kill uiserver

- name: Menu bar | Show bluetooth
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible com.apple.menuextra.bluetooth"
    type: bool
    value: true
  notify: kill uiserver

- name: Photos | Do not launch with hot plug
  osx_defaults:
    domain: com.apple.ImageCapture
    key: disableHotPlug
    type: bool
    value: true

- name: Safari | Developer menu
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: bool
    value: true

- name: Safari | Developer menu
  osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: bool
    value: true

- name: Safari | Developer menu
  osx_defaults:
    domain: com.apple.Safari
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
    type: bool
    value: true

- name: Safari | Show Debug menu
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true

- name: Safari | Show Debug menu
  osx_defaults:
    key: WebKitDeveloperExtras
    type: bool
    value: true

- name: App Store | Show Debug menu
  osx_defaults:
    domain: com.apple.appstore
    key: ShowDebugMenu
    type: bool
    value: true

- name: Dock | Quick autohide
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: int
    value: 1
  notify: kill dock

- name: Dock | Quick autohide
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  notify: kill dock

- name: Dock | Autohide
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify: kill dock

- name: Dock | Size
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 48
  notify: kill dock

- name: Dock | No persistent apps
  osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: []
  notify: kill dock

- name: Dock | Quick expose
  osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.1
  notify: kill dock

- name: Dock | Magnification
  osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: true
  notify: kill dock

- name: Dock | Make hidden applications' icons translucent
  osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
  notify: kill dock

- name: Dock | Show only running applications
  osx_defaults:
    domain: com.apple.dock
    key: static-only
    type: bool
    value: true
  notify: kill dock

- name: Dock | Dashboard disabled
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true
  notify: kill dock

- name: Finder | Show all extensions
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true
  notify: kill finder

- name: Finder | Show all files
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: kill finder

- name: Finder | Home folder on new windows
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfHm
  notify: kill finder

- name: Finder | Search the current folder first
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
  notify: kill finder

- name: Finder | Show items in a list
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: clmv
  notify: kill finder

- name: Finder | Disable slow animations on shift
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableSlowAnimation
    type: bool
    value: false
  notify: kill finder

- name: Finder | Quicklook hide on defocus
  osx_defaults:
    domain: com.apple.finder
    key: QLHidePanelOnDeactivate
    type: bool
    value: true
  notify: kill finder

- name: Finder | Full paths in title
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
  notify: kill finder

- name: Finder | Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: true
  notify: kill finder

- name: Finder | Show "Quit Finder" menu item
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true
  notify: kill finder

- name: Finder | Disable animation when opening the Info window
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true
  notify: kill finder

- name: DesktopService | Do not create .DS_Store on network drives
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: DesktopService | Do not create .DS_Store on usb drives
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

- name: Screen capture | Location for screen capture
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: "~/Screenshots"
  notify: kill uiserver

- name: Screen capture | Type of screen capture
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
  notify: kill uiserver

- name: Printing | Quit Printer App after print job complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true

- name: CrashReporter | Make crash reporter as a notification
  osx_defaults:
    domain: com.apple.CrashReporter
    key: UseUNC
    type: int
    value: 1

- name: Show $HOME/Library
  command: chflags nohidden ~/Library
