---
- name: Setup my Mac
  hosts: localhost
  connection: local
  gather_facts: no
  environment:
    HOMEBREW_NO_ANALYTICS: 1
  
  roles:
    - { role: homebrew, tags: [ homebrew ] }
    - { role: mas, tags: [ mas ] }
    - { role: defaults, tags: [ defaults ] }

  vars_prompt:
    - name: "mas_email"
      prompt: "Apple ID for mas"
      private: no
    - name: "mas_password"
      prompt: "Password for mas"
