---
- name: Setup my Mac
  hosts: mac
  connection: local
  environment:
    HOMEBREW_NO_ANALYTICS: 1

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - dotfiles
    - fonts
    - mas
    - defaults
    - fish
    - firewall
    - iterm2
    - vscode
    - divvy
    - browser

  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    current_user: "{{ lookup('env', 'USER') }}"

  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "sudo password"
    - name: "mas_email"
      prompt: "Apple ID for mas"
      private: no
    - name: "mas_password"
      prompt: "Password for mas"
