- name: kill dock
  command: killall Dock

- name: kill finder
  command: killall Finder

- name: kill uiserver
  command: killall SystemUIServer

- name: kill touch bar agent
  command: "{{ item }}"
  with_items:
    - pkill TouchBarServer
    - killall ControlStrip
  become: yes
  when: (touchbar_process.rc == 0)
