---
- name: Ensure mas is installed.
  homebrew: name=mas state=present

- name: Get mas account status
  register: result
  ignore_errors: yes
  command: mas account

- name: Sign in to MAS
  command: >
    mas signin "{{ mas_email }}" "{{ mas_password }}"
  when: result|failed

- name: Install applications via mas
  command: mas install "{{ item.id }}"
  with_items: "{{ mas_apps }}"
