- name: update brew
  register: result
  ignore_errors: True
  command: >
    brew update

#- name: get brew installer
#  get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install dest=/tmp/brew_install
#  when: result|failed

#- name: proceed brew installer
#  command: >
#    ruby /tmp/brew_install
#  when: result|failed

- name: Install homebrew
  shell: >
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: result|failed

#- name: Download Brewfile
#  command:

- name: Check if Brewfile contains updates
#  shell: brew bundle check --file="{{brewfile|default(Brewfile)}}"
  shell: brew bundle check --file="{{ role_path }}/files/Brewfile"
  register: bundle_check_result
  ignore_errors: true
  environment:
    HOMEBREW_NO_ANALYTICS: 1

- name: Install apps using Brewfile
  shell: brew bundle install --file="{{ role_path }}/files/Brewfile"
  when: bundle_check_result|failed
  environment:
    HOMEBREW_NO_ANALYTICS: 1


