---
- name: Check if Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew


- name: Install Homebrew
  shell: >
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not(homebrew.stat.exists and homebrew.stat.executable)

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Add Homebrew tap repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_taps }}"

- name: Install OSXFUSE
  homebrew_cask:
    name: osxfuse
    sudo_password: "{{ ansible_become_pass }}"

- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.args|default() }}"
  with_items: "{{ homebrew_packages }}"


- name: Install Homebrew-Cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    sudo_password: "{{ ansible_become_pass }}"
  with_items: "{{ homebrew_cask_packages }}"
